<?php

/**
 * Turba Attributes File.
 *
 * This file contains examples of attributes that Turba understands, and their
 * types.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE!
 * Local overrides MUST be placed in var/config/turba/attributes.local.php or
 * var/config/turba/attributes.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use var/config/turba/attributes-servername.php.
 *
 * The syntax of this array is as follows:
 * <pre>
 * label - The text that the user will see attached to this field.
 * type - One of the following:
 *   - spacer            - header
 *   - description       - html
 *   - number            - int
 *   - intlist           - text
 *   - longtext          - countedtext
 *   - address           - file
 *   - boolean           - link
 *   - email             - emailconfirm
 *   - password          - passwordconfirm
 *   - enum              - multienum
 *   - radio             - set
 *   - date              - time
 *   - monthyear         - monthdayyear
 *   - colorpicker       - sorter
 *   - creditcard        - invalid
 *   - stringlist        - addresslink
 * required - Boolean whether this field is mandatory.
 * readonly - Boolean whether this field is editable.
 * desc - Any help text attached to this field.
 * default - The default value for this field.
 * time_object_label - The text to describe the time object category.
 *                     Only valid for monthdayyear types and removing this
 *                     from a monthdayyear type will hide it from the
 *                     listTimeObjects api.
 * params - Any other parameters that need to be passed to the
 *          field. For a documentation of available field
 *          parameters see: http://wiki.horde.org/Doc/Dev/FormTypes.
 *
 * IMPORTANT CHANGE IN HORDE 6 / TURBA 5:
 * ---------------------------------------
 * Date field formatting (monthdayyear, datetime) is now controlled by user
 * preferences, NOT by 'format_out' parameter in this config file.
 *
 * Do NOT specify 'format_out' for date fields - it will be automatically
 * applied from the user's date_format preference at runtime.
 *
 * See the detailed docblock before $attributes['birthday'] for complete
 * documentation on date field configuration.
 * </pre>
 */

/* Personal stuff. */
$attributes['name'] = [
    'label' => _("Name"),
    'type' => 'text',
    'required' => true,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['firstname'] = [
    'label' => _("First Name"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['lastname'] = [
    'label' => _("Last Name"),
    'type' => 'text',
    'required' => true,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['middlenames'] = [
    'label' => _("Middle Names"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['namePrefix'] = [
    'label' => _("Name Prefixes"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 32, 'maxlength' => 32],
];
$attributes['nameSuffix'] = [
    'label' => _("Name Suffixes"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 32, 'maxlength' => 32],
];
$attributes['alias'] = [
    'label' => _("Alias"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 32],
];
$attributes['nickname'] = [
    'label' => _("Nickname"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 32, 'maxlength' => 32],
];
$attributes['yomifirstname'] = [
    'label' => _("Phonetic First Name"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['yomilastname'] = [
    'label' => _("Phonetic Last Name"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];

/**
 * DATE FIELD FORMAT CONFIGURATION
 *
 * IMPORTANT: Do NOT specify 'format_out' parameter for date fields
 * (monthdayyear, datetime) in this configuration file.
 *
 * The user preference for date display formatting is now handled in application code.
 *
 * Why this changed:
 * - Config files should not hook into framework runtime internals but be mostly declarative.
 *
 * Migration from old config:
 *   OLD (Horde 5 / Turba 4): 'format_out' => $GLOBALS['prefs']->getValue('date_format')
 *   NEW (Horde 6 / Turba 5): Omit 'format_out' - automatically applied
 *
 * Supported parameters for date fields:
 *   - start_year: Newest year available in picker (default: current year)
 *   - end_year: Oldest year available in picker dropdown (default: 1900)
 *   - picker: Show date picker widget (default: true)
 *   - format_in: Format for storage/API (default: 'yyyy-MM-dd')
 *   - format_out: DO NOT USE - automatically set from user preference
 *
 * Example correct configuration:
 *   'params' => array(
 *       'start_year' => date('Y'),
 *       'end_year' => 1900,
 *       'picker' => true,
 *       'format_in' => 'yyyy-MM-dd'
 *       // Note: format_out intentionally omitted
 *   )
 *
 * @see Turba_Application::_normalizeDateAttributes() for implementation
 * @since Turba 5.0.0 (Horde 6.0.0)
 */
$attributes['birthday'] = [
    'label' => _("Birthday"),
    'type' => 'monthdayyear',
    'required' => false,
    'params' => ['start_year' => date('Y'), 'end_year' => 1900, 'picker' => true, 'format_in' => 'yyyy-MM-dd'],
    'time_object_label' => _("Birthdays"),
];
$attributes['anniversary'] = [
    'label' => _("Anniversary"),
    'type' => 'monthdayyear',
    'params' => ['start_year' => date('Y'), 'end_year' => 1900, 'picker' => true, 'format_in' => 'yyyy-MM-dd'],
    'required' => false,
    'time_object_label' => _("Anniversaries"),
];
$attributes['spouse'] = [
    'label' => _("Spouse"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['children'] = [
    'label' => _("Children"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['photo'] = [
    'label' => _("Photo"),
    'type' => 'image',
    'required' => false,
    'params' => ['show_upload' => true, 'show_keeporig' => true, 'max_filesize'  => null],
];
$attributes['photo_orig'] = [
    'label' => _("Original Photo"),
    'type' => 'image',
    'required' => false,
    'params' => ['show_upload' => false, 'show_keeporig' => true, 'max_filesize'  => null],
];
$attributes['phototype'] = [
    'label' => _("Photo MIME Type"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];

/* Locations, addresses. */
$attributes['homeAddress'] = [
    'label' => _("Home Address"),
    'type' => 'address',
    'required' => false,
    'params' => ['rows' => 3, 'cols' => 40],
];
$attributes['homeStreet'] = [
    'label' => _("Home Street Address"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['homePOBox'] = [
    'label' => _("Home Post Office Box"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 10, 'maxlength' => 10],
];
$attributes['homeCity'] = [
    'label' => _("Home City"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['homeProvince'] = [
    'label' => _("Home State/Province"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['homePostalCode'] = [
    'label' => _("Home Postal Code"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 10, 'maxlength' => 10],
];
$attributes['homeCountry'] = [
    'label' => _("Home Country"),
    'type' => 'country',
    'required' => false,
    'params' => ['prompt' => true],
];
$attributes['homeCountryFree'] = [
    'label' => _("Home Country"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['workAddress'] = [
    'label' => _("Work Address"),
    'type' => 'address',
    'required' => false,
    'params' => ['rows' => 3, 'cols' => 40],
];
$attributes['workStreet'] = [
    'label' => _("Work Street Address"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['workPOBox'] = [
    'label' => _("Work Post Office Box"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 10, 'maxlength' => 10],
];
$attributes['workCity'] = [
    'label' => _("Work City"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['workProvince'] = [
    'label' => _("Work State/Province"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['workPostalCode'] = [
    'label' => _("Work Postal Code"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 10, 'maxlength' => 10],
];
$attributes['workCountry'] = [
    'label' => _("Work Country"),
    'type' => 'country',
    'required' => false,
    'params' => ['prompt' => true],
];
$attributes['workCountryFree'] = [
    'label' => _("Work Country"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['companyAddress'] = [
    'label' => _("Company Address"),
    'type' => 'address',
    'required' => false,
    'params' => ['rows' => 3, 'cols' => 40],
];
$attributes['otherAddress'] = [
    'label' => _("Other Address"),
    'type' => 'address',
    'required' => false,
    'params' => ['rows' => 3, 'cols' => 40],
];
$attributes['otherStreet'] = [
    'label' => _("Other Street Address"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['otherCity'] = [
    'label' => _("Other City"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['otherProvince'] = [
    'label' => _("Other State/Province"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['otherPostalCode'] = [
    'label' => _("Other Postal Code"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 10, 'maxlength' => 10],
];
$attributes['otherCountry'] = [
    'label' => _("Other Country"),
    'type' => 'country',
    'required' => false,
    'params' => ['prompt' => true],
];
$attributes['otherCountryFree'] = [
    'label' => _("Other Country"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['otherPOBox'] = [
    'label' => _("Other Post Office Box"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 10, 'maxlength' => 10],
];
$attributes['timezone'] = [
    'label' => _("Time Zone"),
    'type' => 'enum',
    'params' => ['values' => Horde_Nls::getTimezones(), 'prompt' => true],
    'required' => false,
];

/* Communication. */
$attributes['email'] = [
    'label' => _("Email"),
    'type' => 'email',
    'required' => false,
    'params' => ['allow_multi' => false, 'strip_domain' => false, 'link_compose' => true, 'link_name' => null, 'delimiters' => ',', 'size' => null],
];
$attributes['emails'] = [
    'label' => _("Emails"),
    'type' => 'email',
    'required' => false,
    'params' => ['allow_multi' => true, 'strip_domain' => false, 'link_compose' => true, 'link_name' => null, 'delimiters' => ',', 'size' => null],
];
$attributes['homePhone'] = [
    'label' => _("Home Phone"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['homePhone2'] = [
    'label' => _("Home Phone"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['workPhone'] = [
    'label' => _("Work Phone"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['workPhone2'] = [
    'label' => _("Work Phone"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['assistPhone'] = [
    'label' => _("Assistant Phone"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['companyPhone'] = [
    'label' => _("Company Phone"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['cellPhone'] = [
    'label' => _("Mobile Phone"),
    'type' => 'cellphone',
    'required' => false,
];
$attributes['carPhone'] = [
    'label' => _("Car Phone"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['radioPhone'] = [
    'label' => _("Radio Phone"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['fax'] = [
    'label' => _("Fax"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['homeFax'] = [
    'label' => _("Home Fax"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['pager'] = [
    'label' => _("Pager"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['imaddress'] = [
    'label' => _("Instant Messenger"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['imaddress2'] = [
    'label' => _("Instant Messenger"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['imaddress3'] = [
    'label' => _("Instant Messenger"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];

/* Job, company, organization. */
$attributes['title'] = [
    'label' => _("Job Title"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['role'] = [
    'label' => _("Occupation"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['businessCategory'] = [
    'label' => _("Business Category"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['company'] = [
    'label' => _("Company"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['department'] = [
    'label' => _("Department"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['office'] = [
    'label' => _("Office"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['logo'] = [
    'label' => _("Logo"),
    'type' => 'image',
    'required' => false,
    'params' => ['show_upload' => true, 'show_keeporig' => true, 'max_filesize'  => null],
];
$attributes['logotype'] = [
    'label' => _("Logo MIME Type"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];

/* Other */
$attributes['notes'] = [
    'label' => _("Notes"),
    'type' => 'longtext',
    'required' => false,
    'params' => ['rows' => 3, 'cols' => 40],
];
$attributes['website'] = [
    'label' => _("Website URL"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['freebusyUrl'] = [
    'label' => _("Freebusy URL"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
/**
 * TODO: Find a way to move globals access out of this use case, too
 */
if (!empty($GLOBALS['conf']['gnupg']['path'])) {
    $attributes['pgpPublicKey'] = [
        'label' => _("PGP Public Key"),
        'type' => 'pgp',
        'required' => false,
        'params' => ['gpg' => $GLOBALS['conf']['gnupg']['path'], 'temp_dir' => Horde::getTempDir(), 'rows' => 3, 'cols' => 40],
    ];
} else {
    $attributes['pgpPublicKey'] = [
        'label' => _("PGP Public Key"),
        'type' => 'longtext',
        'required' => false,
        'params' => ['rows' => 3, 'cols' => 40],
    ];
}
$attributes['smimePublicKey'] = [
    'label' => _("S/MIME Public Certificate"),
    'type' => 'smime',
    'required' => false,
    'params' => ['temp_dir' => Horde::getTempDir(), 'rows' => 3, 'cols' => 40],
];
$attributes['category'] = [
    'label' => _("Category"),
    'type' => 'category',
    'params' => [],
    'required' => false,
];

/* Additional attributes supported by Kolab */
$attributes['kolabHomeServer'] = [
    'label' => _("Kolab Home Server"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['initials'] = [
    'label' => _("Initials"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['manager'] = [
    'label' => _("Manager"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['assistant'] = [
    'label' => _("Assistant"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['gender'] = [
    'label' => _("Gender"),
    'type' => 'enum',
    'required' => false,
    'params' => ['values' => ['male' => _("male"), 'female' => _("female")], 'prompt' => true],
];
$attributes['language'] = [
    'label' => _("Language"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['latitude'] = [
    'label' => _("Latitude"),
    'type' => 'number',
    'required' => false,
];
$attributes['longitude'] = [
    'label' => _("Longitude"),
    'type' => 'number',
    'required' => false,
];

/* Additional attributes supported by some SyncML clients */
$attributes['workEmail'] = [
    'label' => _("Work Email"),
    'type' => 'email',
    'required' => false,
    'params' => ['allow_multi' => false, 'strip_domain' => false, 'link_compose' => true, 'link_name' => null, 'delimiters' => ',', 'size' => null],
];
$attributes['homeEmail'] = [
    'label' => _("Home Email"),
    'type' => 'email',
    'required' => false,
    'params' => ['allow_multi' => false, 'strip_domain' => false, 'link_compose' => true, 'link_name' => null, 'delimiters' => ',', 'size' => null],
];
$attributes['phone'] = [
    'label' => _("Common Phone"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['workFax'] = [
    'label' => _("Work Fax"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['workCellPhone'] = [
    'label' => _("Work Mobile Phone"),
    'type' => 'cellphone',
    'required' => false,
];
$attributes['homeCellPhone'] = [
    'label' => _("Home Mobile Phone"),
    'type' => 'cellphone',
    'required' => false,
];
$attributes['videoCall'] = [
    'label' => _("Common Video Call"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['workVideoCall'] = [
    'label' => _("Work Video Call"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['homeVideoCall'] = [
    'label' => _("Home Video Call"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['voip'] = [
    'label' => _("VoIP"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['sip'] = [
    'label' => _("SIP"),
    'type' => 'email',
    'required' => false,
    'params' => ['allow_multi' => true, 'strip_domain' => false, 'link_compose' => true, 'link_name' => null, 'delimiters' => ',', 'size' => null],
];
$attributes['ptt'] = [
    'label' => _("PTT"),
    'type' => 'phone',
    'required' => false,
    'params' => ['size' => 15],
];
$attributes['commonExtended'] = [
    'label' => _("Common Address Extended"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['commonStreet'] = [
    'label' => _("Common Street"),
    'type' => 'address',
    'required' => false,
    'params' => ['rows' => 3, 'cols' => 40],
];
$attributes['commonPOBox'] = [
    'label' => _("Common Post Office Box"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 10, 'maxlength' => 10],
];
$attributes['commonCity'] = [
    'label' => _("Common City"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['commonProvince'] = [
    'label' => _("Common State/Province"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['commonPostalCode'] = [
    'label' => _("Common Postal Code"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 10, 'maxlength' => 10],
];
$attributes['commonCountry'] = [
    'label' => _("Common Country"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['commonCountryFree'] = [
    'label' => _("Common Country"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['workWebsite'] = [
    'label' => _("Work Website URL"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['workExtended'] = [
    'label' => _("Work Address Extended"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['workLatitude'] = [
    'label' => _("Work Latitude"),
    'type' => 'number',
    'required' => false,
];
$attributes['workLongitude'] = [
    'label' => _("Work Longitude"),
    'type' => 'number',
    'required' => false,
];
$attributes['homeWebsite'] = [
    'label' => _("Home Website URL"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['homeExtended'] = [
    'label' => _("Home Address Extended"),
    'type' => 'text',
    'required' => false,
    'params' => ['regex' => '', 'size' => 40, 'maxlength' => 255],
];
$attributes['homeLatitude'] = [
    'label' => _("Home Latitude"),
    'type' => 'number',
    'required' => false,
];
$attributes['homeLongitude'] = [
    'label' => _("Home Longitude"),
    'type' => 'number',
    'required' => false,
];
$attributes['__tags'] = [
    'label' => _("Tags"),
    'type' => 'Turba:TurbaTags',
    'required' => false,
];
