<?php

/**
 * MIME Viewer configuration for Turba.
 *
 * Settings in this file override settings in horde/config/mime_drivers.php.
 * All drivers configured in that file, but not configured here, will also
 * be used to display MIME content.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE!
 * Local overrides MUST be placed in var/config/turba/mime_drivers.local.php or
 * var/config/turba/mime_drivers.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use var/config/turba/mime_drivers-servername.php.
 */

/* By default, Turba uses the default Horde-wide settings contained in
 * horde/config/mime_drivers.php. */
