<?php
// ADMINISTRATORS: Do not edit this file. Put custom routes into var/config/turba/routes.local.php and run composer horde:reconfigure
namespace Horde\Turba;

use Horde\Core\Middleware\DefaultStack;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

// Admin Routes — must come before catch-all or wildcard routes

$mapper->buildRoute(uri: '/admin/schematest', name: 'AdminSchemaTest')
    ->withController(Controller\AdminSchemaTestController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->withMiddleware(DefaultStack::get())
    ->add();

// Responsive UI Routes - PSR-style builder pattern

// Contacts List - Primary route with legacy smartmobile secondary
$mapper->buildRoute(uri: '/responsive', name: 'ResponsiveContacts')
    ->withController(Responsive\ResponsiveController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/smartmobile')
    ->withSecondaryRoute('/smartmobile.php')
    ->add();

// Contact Detail View
$mapper->buildRoute(uri: '/responsive/contact/:source/:key', name: 'ResponsiveContact')
    ->withController(Responsive\ResponsiveController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->requires('source', '[a-zA-Z0-9\-_]+')
    ->requires('key', '[^/]+')
    ->withMiddleware(DefaultStack::get())
    ->add();

// Contact Export
$mapper->buildRoute(uri: '/responsive/export/:source/:key', name: 'ResponsiveExport')
    ->withController(Responsive\ResponsiveController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->requires('source', '[a-zA-Z0-9\-_]+')
    ->requires('key', '[^/]+')
    ->withMiddleware(DefaultStack::get())
    ->add();

// Add New Contact
$mapper->buildRoute(uri: '/responsive/add', name: 'ResponsiveAdd')
    ->withController(Responsive\ResponsiveController::class)
    ->withDefaults(['HordeAuthType' => 'authenticate'])
    ->withMiddleware(DefaultStack::get())
    ->add();
