<?php
// ADMINISTRATORS: Do not edit this file. Put custom routes into var/config/turba/routes.local.php and run composer horde:reconfigure
namespace Horde\Turba;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

// Responsive UI Routes
$mapper->connect(
    'ResponsiveContacts',
    '/responsive',
    [
        'controller' => Responsive\ResponsiveController::class,
        'HordeAuthType' => 'authenticate',
        'stack' => [],
    ]
);

$mapper->connect(
    'ResponsiveContact',
    '/responsive/contact/:source/:key',
    [
        'controller' => Responsive\ResponsiveController::class,
        'HordeAuthType' => 'authenticate',
        'stack' => [],
    ]
);

$mapper->connect(
    'ResponsiveExport',
    '/responsive/export/:source/:key',
    [
        'controller' => Responsive\ResponsiveController::class,
        'HordeAuthType' => 'authenticate',
        'stack' => [],
    ]
);

$mapper->connect(
    'ResponsiveAdd',
    '/responsive/add',
    [
        'controller' => Responsive\ResponsiveController::class,
        'HordeAuthType' => 'authenticate',
        'stack' => [],
    ]
);
